name: cat_trivia
description: Cat Trivia
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
  intl: ^0.18.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  dio: ^5.1.2
  retrofit: ^4.0.1
  logger: ^1.3.0
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Widgets dependencies
  shimmer: ^3.0.0
  very_good_infinite_list: ^0.7.0
  

dev_dependencies:
  very_good_analysis: ^5.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  retrofit_generator: ^8.0.2
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
